"""Update Bid model: change day to DateTime

Revision ID: 4d40116a1259
Revises: c5e3413f9ec7
Create Date: 2025-09-08 01:12:50.453751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d40116a1259'
down_revision: Union[str, Sequence[str], None] = 'c5e3413f9ec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
